---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.cf-worker
  resources:
  - jobbuilders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cf-worker
  resources:
  - jobbuilders/finalizers
  verbs:
  - update
- apiGroups:
  - api.cf-worker
  resources:
  - jobbuilders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - api.cf-worker
  resources:
  - workeraccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cf-worker
  resources:
  - workeraccounts/finalizers
  verbs:
  - update
- apiGroups:
  - api.cf-worker
  resources:
  - workeraccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - api.cf-worker
  resources:
  - workerbundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cf-worker
  resources:
  - workerbundles/finalizers
  verbs:
  - update
- apiGroups:
  - api.cf-worker
  resources:
  - workerbundles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - api.cf-worker
  resources:
  - workerdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cf-worker
  resources:
  - workerdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - api.cf-worker
  resources:
  - workerdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - api.cf-worker
  resources:
  - workerreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cf-worker
  resources:
  - workerreleases/finalizers
  verbs:
  - update
- apiGroups:
  - api.cf-worker
  resources:
  - workerreleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - api.cf-worker
  resources:
  - workerversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cf-worker
  resources:
  - workerversions/finalizers
  verbs:
  - update
- apiGroups:
  - api.cf-worker
  resources:
  - workerversions/status
  verbs:
  - get
  - patch
  - update
