# permissions for end users to edit workerreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workerrelease-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: workerbundle
    app.kubernetes.io/part-of: workerbundle
    app.kubernetes.io/managed-by: kustomize
  name: workerrelease-editor-role
rules:
- apiGroups:
  - api.cf-worker
  resources:
  - workerreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cf-worker
  resources:
  - workerreleases/status
  verbs:
  - get
