apiVersion: api.cf-worker/v1
kind: WorkerRelease
metadata:
  labels:
    app.kubernetes.io/name: workerrelease
    app.kubernetes.io/instance: workerrelease-sample
    app.kubernetes.io/part-of: workerbundle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: workerbundle
  name: workerrelease-sample
spec:
  # TODO(user): Add fields here
