apiVersion: api.cf-worker/v1
kind: WorkerAccount
metadata:
  labels:
    app.kubernetes.io/name: workeraccount
    app.kubernetes.io/instance: workeraccount-sample
    app.kubernetes.io/part-of: workerbundle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: workerbundle
  name: workeraccount-sample
spec:
  workerBundleName: worker-bundle-name
  workerReleaseSelector:
    matchLabels:
      accounts: "1234"
  podTemplate:
    imagePullSecret: "insert-secret-here"