apiVersion: api.cf-worker/v1
kind: JobBuilder
metadata:
  labels:
    app.kubernetes.io/name: jobbuilder
    app.kubernetes.io/instance: jobbuilder-sample
    app.kubernetes.io/part-of: workerbundle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: workerbundle
    accounts: "1234"
  name: "1234" #accounts
spec:
  scriptNames:
    - wasm-worker
    - hello
  scriptUrls:
    - s3://stage-cf-worker/398803b74bcdb1b454434669bc634190/wasm-worker
    - s3://stage-cf-worker/398803b74bcdb1b454434669bc634190/hello
  targetImage: clementreiffers/artist-worker
  workerBundleName: worker-bundle-name