apiVersion: api.cf-worker/v1
kind: WorkerRelease
metadata:
  labels:
    app.kubernetes.io/name: workerrelease
    app.kubernetes.io/instance: workerrelease-sample
    app.kubernetes.io/part-of: workerbundle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: workerbundle
  name: "1234" #accounts
spec:
  scriptName: wasm-worker
  secretRef: "secret-accounts-ref" # prefix WASM_WORKER_ toutes les var d'env
  compatibilityDate: "MM/DD/YYYY"
  scriptUrls:
    - "s3://path/to/dir/version/files1"
    - "s3://path/to/dir/version/files2"