clean:
	kubectl delete crd workeraccounts.api.cf-worker
	kubectl delete crd jobbuilders.api.cf-worker
	kubectl delete crd workerbundles.api.cf-worker
	kubectl delete crd workerdeployments.api.cf-worker
	kubectl delete crd workerreleases.api.cf-worker
	kubectl delete crd workerversions.api.cf-worker