apiVersion: v1
kind: Service
metadata:
  name: {{ include "fire-worker.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: workerbundle
    app.kubernetes.io/part-of: workerbundle
    control-plane: controller-manager
  {{- include "fire-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "fire-worker.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}