apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fire-worker.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: workerbundle
    app.kubernetes.io/part-of: workerbundle
  {{- include "fire-worker.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}